const ads = [
  // ─── ABSURD ───────────────────────────────────────────
  {
    id: "aircube-001",
    theme: "absurd",
    brand: "AirCube®",
    icon: "🌬️",
    image: "/public/images/aircube.jpg",
    accentColor: "#0A90B4",
    ctaBg: "#C0E8F0",
    ctaColor: "#0A4A5C",
    sizes: {
      rectangle: {
        eyebrow: "Now Available",
        headline: "Premium Subscription Air",
        copy: "Why breathe free air like some kind of animal? AirCube delivers artisanal, cold-pressed atmospheric molecules to your home. Monthly. $79/mo.",
        cta: "Inhale Now",
      },
      banner: {
        headline: "AirCube®",
        copy: "Subscription air for people with too much money. $79/mo.",
        cta: "Breathe Premium",
      },
      native: {
        headline: "Is Your Air Disrupting Your Productivity? AirCube® Thinks So.",
        copy: "A new study commissioned by AirCube® found that 97% of people breathe air. Their solution costs $79/mo and arrives in a cube. Analysts are baffled.",
        tag: "Promoted · AirCube®",
        cta: "Read More",
      },
    },
  },
  {
    id: "blorb-001",
    theme: "absurd",
    brand: "Blorb®",
    icon: "🥄",
    image: "/public/images/blorb.jpg",
    accentColor: "#7B40D4",
    ctaBg: "#7B40D4",
    ctaColor: "#fff",
    sizes: {
      rectangle: {
        eyebrow: "Blockchain-Powered",
        headline: "The World's First Web3 Spoon",
        copy: "Every stir is a transaction. Every bite, a block. Blorb® puts your soup on the blockchain, where it belongs. NFTs included. Flavor sold separately.",
        cta: "Mint Yours",
      },
      banner: {
        headline: "Blorb®",
        copy: "Your soup. On the blockchain. No, really. Gas fees may apply.",
        cta: "Mint a Spoon",
      },
      native: {
        headline: "Meet Blorb®: The Spoon That's Also a Smart Contract",
        copy: "We sat down with the founders of Blorb® to discuss why soup needed decentralization and what 'immutable broth' actually means for the future of eating.",
        tag: "Paid Content · Blorb®",
        cta: "Read More",
      },
    },
  },
  {
    id: "nothingburger-001",
    theme: "absurd",
    brand: "NothingBurger™",
    icon: "🍔",
    image: "/public/images/nothingburger.jpg",
    accentColor: "#D4420A",
    ctaBg: "#1A1814",
    ctaColor: "#F5F2EC",
    sizes: {
      rectangle: {
        eyebrow: "Finally",
        headline: "Taste the Void",
        copy: "Zero calories. Zero flavor. Zero ingredients. NothingBurger™ is the world's most honest food product. Pairs well with existential dread.",
        cta: "Order Zero",
      },
      banner: {
        headline: "NothingBurger™",
        copy: "Now with 0% more everything. Fast casual nihilism. Free delivery on orders over nothing.",
        cta: "Order Nothing",
      },
      native: {
        headline: "NothingBurger™ Raises $40M to Disrupt the Food Industry by Removing Food",
        copy: "Silicon Valley's boldest food startup promises to solve hunger by reframing it as 'intentional fasting as a service.' Investors are eating it up. Literally.",
        tag: "Sponsored · NothingBurger™",
        cta: "Read More",
      },
    },
  },
  {
    id: "gravlplus-001",
    theme: "absurd",
    brand: "Gravel+",
    icon: "🪨",
    image: "/public/images/gravelplus.jpg",
    accentColor: "#8C7A68",
    ctaBg: "#5C5048",
    ctaColor: "#F8F5F0",
    sizes: {
      rectangle: {
        eyebrow: "Monthly Delivery",
        headline: "Premium Subscription Gravel",
        copy: "Hand-selected stones, ethically sourced from the ground. Our sommeliers curate each month's gravel based on your personality type and moon phase.",
        cta: "Get Stoned",
      },
      banner: {
        headline: "Gravel+",
        copy: "Artisanal subscription gravel, delivered monthly. Curated by moonlight.",
        cta: "Subscribe to Rocks",
      },
      native: {
        headline: "The Gravel Revolution: Why Millennials Are Paying $49/mo for Rocks",
        copy: "Gravel+ has quietly become the fastest-growing subscription box in the Pacific Northwest. We investigate whether premium gravel is the new olive oil.",
        tag: "Promoted · Gravel+",
        cta: "Read More",
      },
    },
  },
  {
    id: "scentcoin-001",
    theme: "absurd",
    brand: "ScentCoin™",
    icon: "👃",
    accentColor: "#B4700A",
    ctaBg: "#EF9F27",
    ctaColor: "#2A1800",
    sizes: {
      rectangle: {
        eyebrow: "Web3 Meets Wellness",
        headline: "Tokenize Your Nose",
        copy: "ScentCoin™ lets you earn crypto every time you smell something. Simply inhale, confirm the transaction, and watch your nasal portfolio grow.",
        cta: "Sniff to Earn",
      },
      banner: {
        headline: "ScentCoin™",
        copy: "Earn crypto by smelling things. DeFi meets your nostrils. APY: unverifiable.",
        cta: "Sniff to Earn",
      },
      native: {
        headline: "This Startup Pays You in Crypto to Smell Things. We Tried It.",
        copy: "ScentCoin™ promises up to $400/month for active sniffers. We tested the protocol for two weeks. Our nose hurts. Our wallet is empty. We have thoughts.",
        tag: "Sponsored · ScentCoin™",
        cta: "Read More",
      },
    },
  },
  {
    id: "sleepcorp-001",
    theme: "absurd",
    brand: "DreamLease™",
    icon: "😴",
    accentColor: "#5340A0",
    ctaBg: "#3B2880",
    ctaColor: "#E8E0FF",
    sizes: {
      rectangle: {
        eyebrow: "Sleep Tech",
        headline: "Rent Your Dreams. Monthly.",
        copy: "DreamLease™ streams HD dreams directly to your subconscious via a proprietary pillow API. Cancel anytime. Some nightmares require Premium tier.",
        cta: "Start Dreaming",
      },
      banner: {
        headline: "DreamLease™",
        copy: "Subscription dream streaming. 4K REM. Cancel anytime. Nightmares are Premium.",
        cta: "Start Free Trial",
      },
      native: {
        headline: "DreamLease™ Claims to Stream Dreams via Pillow. The FDA Has Questions.",
        copy: "The startup says its proprietary pillow API can 'push' dream content while you sleep. 12,000 beta users report varying results. Two woke up speaking Portuguese.",
        tag: "Paid Content · DreamLease™",
        cta: "Read More",
      },
    },
  },

  // ─── CORPORATE ────────────────────────────────────────
  {
    id: "blandco-001",
    theme: "corporate",
    brand: "BlandCo™",
    icon: "📊",
    image: "/public/images/blandco.jpg",
    accentColor: "#1A3A5C",
    ctaBg: "#1A3A5C",
    ctaColor: "#fff",
    sizes: {
      rectangle: {
        eyebrow: "Introducing",
        headline: "Synergizing Your Synergies",
        copy: "We leverage cutting-edge nothing to deliver end-to-end solutions for problems you didn't know you had. Enterprise-grade. Cloud-native. Completely hollow.",
        cta: "Learn More",
      },
      banner: {
        headline: "BlandCo™",
        copy: "B2B solutions for your B2B solutions. Enterprise-grade. Cloud-native. Meaningless.",
        cta: "Request a Demo",
      },
      native: {
        headline: "How BlandCo™ Used Agile Methodologies to Pivot Their Pivot",
        copy: "A thought leader explores the intersection of synergy, disruption, and proactive paradigm shifts in today's dynamic ecosystem. Spoiler: it's just a spreadsheet.",
        tag: "Sponsored · BlandCo™",
        cta: "Read More",
      },
    },
  },
  {
    id: "infinitepdf-001",
    theme: "corporate",
    brand: "InfinitePDF",
    icon: "📄",
    image: "/public/images/infinitepdf.jpg",
    accentColor: "#E8380A",
    ctaBg: "#E8380A",
    ctaColor: "#fff",
    sizes: {
      rectangle: {
        eyebrow: "Enterprise Solution",
        headline: "Convert Your Feelings Into Actionable PDFs",
        copy: "With InfinitePDF, your emotions become deliverables. Export grief as a 47-page report. Schedule anxiety as a calendar event. SOC 2 compliant.",
        cta: "Start Free Trial",
      },
      banner: {
        headline: "InfinitePDF",
        copy: "Your feelings, formatted. Export grief. Import clarity. SOC 2 compliant. Free 14-day trial.",
        cta: "Start Free Trial",
      },
      native: {
        headline: "Why Every Fortune 500 Company Is Converting Their Emotions to PDF",
        copy: "Q3 feelings. Q4 regrets. With InfinitePDF, your inner life finally has version control. We spoke to the CTO about what 'emotionally agile' actually means.",
        tag: "Sponsored · InfinitePDF",
        cta: "Read More",
      },
    },
  },
  {
    id: "vaguemetrics-001",
    theme: "corporate",
    brand: "VagueMetrics™",
    icon: "📈",
    accentColor: "#1D6B44",
    ctaBg: "#1D6B44",
    ctaColor: "#fff",
    sizes: {
      rectangle: {
        eyebrow: "Data-Driven",
        headline: "Measure Everything. Understand Nothing.",
        copy: "VagueMetrics™ gives your team 10,000 dashboards, 400 KPIs, and zero insight. Finally, analytics that feel busy. Integrates with everything. Clarifies nothing.",
        cta: "See the Numbers",
      },
      banner: {
        headline: "VagueMetrics™",
        copy: "10,000 dashboards. 400 KPIs. Zero insight. Data-driven decisions for the modern enterprise.",
        cta: "Book a Demo",
      },
      native: {
        headline: "VagueMetrics™ Named Leader in Gartner Magic Quadrant for Confusing Analytics",
        copy: "For the third year running, VagueMetrics™ has been recognized for delivering the most comprehensive set of metrics that no one at the company fully understands.",
        tag: "Paid Content · VagueMetrics™",
        cta: "Read More",
      },
    },
  },
  {
    id: "pivotware-001",
    theme: "corporate",
    brand: "Pivotware™",
    icon: "🔄",
    accentColor: "#8B4513",
    ctaBg: "#6B340F",
    ctaColor: "#FFF8F0",
    sizes: {
      rectangle: {
        eyebrow: "SaaS Platform",
        headline: "The Operating System for Your Roadmap's Roadmap",
        copy: "Pivotware™ helps teams align on priorities, then re-align, then align on the re-alignment. Used by 200+ companies currently in the middle of a major pivot.",
        cta: "Align Now",
      },
      banner: {
        headline: "Pivotware™",
        copy: "The operating system for your roadmap's roadmap. Alignment as a service. 200+ pivoting customers.",
        cta: "Start Aligning",
      },
      native: {
        headline: "How Pivotware™ Helped One Startup Pivot 14 Times in 18 Months",
        copy: "\"We didn't know what we were building,\" said the CEO, \"but with Pivotware™ we could not-know it much faster and with better documentation.\" Series B closed last week.",
        tag: "Sponsored · Pivotware™",
        cta: "Read More",
      },
    },
  },
  {
    id: "cloudify-001",
    theme: "corporate",
    brand: "Cloudify360°",
    icon: "☁️",
    accentColor: "#1565C0",
    ctaBg: "#1565C0",
    ctaColor: "#fff",
    sizes: {
      rectangle: {
        eyebrow: "Digital Transformation",
        headline: "Put Everything in the Cloud. Twice.",
        copy: "Cloudify360° migrates your legacy systems, your new systems, your hopes, and your filing cabinet to the cloud. Redundant. Scalable. Expensive. Enterprise.",
        cta: "Go Cloudward",
      },
      banner: {
        headline: "Cloudify360°",
        copy: "Your legacy systems, migrated. Your new systems, also migrated. Even the cabinet. Enterprise cloud.",
        cta: "Get a Quote",
      },
      native: {
        headline: "Cloudify360° Says It Can Move Your 'Entire Business' to the Cloud in 90 Days",
        copy: "The claim includes legacy databases, on-prem servers, and—according to the slide deck—'vibes.' The contract is 340 pages. The implementation plan involves a lot of Zoom calls.",
        tag: "Promoted · Cloudify360°",
        cta: "Read More",
      },
    },
  },
];

module.exports = ads;
